# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ErikLearningSec"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/ErikPham141"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/phamphuoc"

[social.params]
icon = "brand-linkedin"
